language: objective-c
osx_image: xcode8

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation -b swift2.3
  - git clone https://github.com/Electrode-iOS/ELDispatch.git ../ELDispatch -b swift2.3
  - git clone https://github.com/Electrode-iOS/ELLog.git ../ELLog -b swift2.3
script:
   - xctool -project ELRouter.xcodeproj -scheme ELRouter -sdk iphonesimulator build test
