language: objective-c
osx_image: xcode7.3

install: 
  - git clone https://github.com/Electrode-iOS/ELFoundation.git ../ELFoundation
  - git clone https://github.com/Electrode-iOS/ELDispatch.git ../ELDispatch
  - git clone https://github.com/Electrode-iOS/ELLog.git ../ELLog
script:
   - xcodebuild -project ELRouter.xcodeproj -scheme ELRouter -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' CODE_SIGNING_REQUIRED=NO
