language: objective-c
osx_image: xcode8.1

install: 
  - carthage bootstrap --no-build
script:
   - xcodebuild -project ELRouter.xcodeproj -scheme ELRouter -sdk iphonesimulator test -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' CODE_SIGNING_REQUIRED=NO
