language: objective-c
osx_image: xcode7.2

install: 
  - git clone https://github.com/TheHolyGrail/ELFoundation.git ../ELFoundation
  - git clone https://github.com/TheHolyGrail/ELDispatch.git ../ELDispatch
  - git clone https://github.com/TheHolyGrail/ELLog.git ../ELLog
script:
   - xctool -project ELRouter.xcodeproj -scheme ELRouter -sdk iphonesimulator build test
